---
title: "SECASC Invasive Species Expert Elicitation Workshop"
description: |
  April 27-28, 2022 <br>
  Austin Cary Forest Campus <br>
  University of Florida, Gainesville, FL
site: distill::distill_website
---

This expert elicitation workshop aims to use expert elicitation to assess invasive species risk throughout the southeastern US. We have developed a purpose built web application that will be used to collate expert knowledge to produce models of current species distributions and future distributions under climate change. The workshop would focus on approximately 10-15 invasive species that are currently, or have the potential to be, highly detrimental to ecosystems of the SE US. These species come from our initial meeting over Zoom in Autumn 2021 where we ranked species. Thus, this first workshop is quite focused on taxonomic expertise in distribution and ecological/trait data. We will then have a second workshop where we explore management options in light of outputs from workshop 1.

This workshop is supported by the Southeast Climate Adaptation Science Center and is hosted by the University of Florida. The workshop leads are:

- Brett Scheffers, Assistant Professor
- Luke Evans, Post-doc
- Alex Baecher, PhD candidate

Invited participants will provide their insight on invasive species habitat suitability and prevalence through an interactive web application created with R Shiny. This web app can be accessed from the [**'App'**](https://joshcullen.github.io/invasive_spp_expert_elicitation/shiny_app.html) tab at the top of the page or through the link to [**shinyapps.io**](https://joshcullen.shinyapps.io/invasive_expert_elicitation/).
